version: "3"
services:
  backend:
    restart: always
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://ruslan:Ruslan1649757@db:5432/lab3 # путь до бд, см. db service
    volumes:
      - ./backend:/backend
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=ruslan
      - POSTGRES_PASSWORD=Ruslan1649757
      - POSTGRES_DB=lab3
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs