version: "3"
services:
  backend:
    restart: always
    build: ./backend
    container_name: backend
    image: rusick/backend
    environment:
      - DATABASE_URL=postgresql://ruslan:Ruslan1649757@db:5432/lab3 # путь до бд, см. db service
    volumes:
      - ./backend:/backend
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=ruslan
      - POSTGRES_PASSWORD=Ruslan1649757
      - POSTGRES_DB=lab3
    volumes:
      - postgres
  frontend:
    container_name: frontend
    image: rusick/frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/frontend/build
    depends_on:
      - backend
      - db
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
    depends_on:
      - frontend
      - backend
volumes:
  frontend_build:
